using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NHibernate;
using NHibernate.Cfg;
using NHibernate.Tool.hbm2ddl;

namespace FirstProject
{
    class MainClass
    {
        public static void Main(String[] args)
        {
            //ISessionFactory sf = new Configuration().Configure().BuildSessionFactory();

            Configuration cfg = new Configuration();
            cfg.Configure();
            SchemaExport s = new SchemaExport(cfg);
            SchemaUpdate su = new SchemaUpdate(cfg);

            Console.WriteLine("-- Instructions generated by SchemaExport");
            s.SetOutputFile("c:/void/schema.sql");
            s.Execute(txt => Console.WriteLine(txt), false, false);

            Console.WriteLine("-- Instructions generated by SchemaUpdate");
            su.Execute(txt => Console.WriteLine(txt), false);

            Console.ReadLine();

        }
    }
}
